config/routes.rb
Bagboy::Engine.routes.draw do

    root to: 'pages#index'

    get   '/update',    to: 'pages#update', as: 'update'

    get   '/signin',    to: 'sessions#new',     as: 'bagboy_signin'
    post  '/signin',    to: 'sessions#create'
    get   '/signout',   to: 'sessions#destroy', as: 'signout'

    get   '/signup', to: 'users#new', as: 'bagboy_signup'
    post  '/signup', to: 'users#create'

    get   '/users',             to: 'users#index',  as: 'users'
    get   '/users/new',         to: 'users#new',    as: 'new_user'
    get   '/users/edit/:id',    to: 'users#edit',   as: 'edit_user'
    post  '/users/edit/:id',    to: 'users#update', as: 'update_user'
    get   '/users/delete/:id',  to: 'users#delete', as: 'delete_user'
    get   '/user/:id',          to: 'users#show',   as: 'user'

    get   '/data_bags/:bag/items/new',          to: 'data_bag_items#new',       as: 'new_data_bag_item'
    post  '/data_bags/:bag/items/new',          to: 'data_bag_items#create',    as: 'create_data_bag_item'
    get   '/data_bags/:bag/items/:item/edit',   to: 'data_bag_items#edit',      as: 'edit_data_bag_item'
    post  '/data_bags/:bag/items/:item/edit',   to: 'data_bag_items#update',    as: 'update_data_bag_item'
    get   '/data_bags/:bag/items/:item',        to: 'data_bag_items#index',     as: 'data_bag_items'

    get   '/data_bags/:bag/template', to: 'data_bag_templates#show',    as: 'data_bag_template'

    post  '/data_bags/:bag/template/item',        to: 'data_bag_template_items#create',   as: 'create_data_bag_template_item'
    post  '/data_bags/:bag/template/item/delete', to: 'data_bag_template_items#delete',   as: 'delete_data_bag_template_item'

    get   '/data_bags',       to: 'data_bags#index',  as: 'data_bags'
    get   '/data_bags/new',   to: 'data_bags#new',    as: 'new_data_bag'
    post  '/data_bags/new',   to: 'data_bags#create', as: 'create_data_bag'
    get   '/data_bags/:bag',  to: 'data_bags#show',   as: 'data_bag'

end

app/models/bagboy/template.rb
module Bagboy
  class Template < ActiveRecord::Base

    before_save :check_id

    def check_id
      data        = parsed_data
      data['id']  = 'text' if data['id'] == nil
      self.data   = data.to_json
    end

    def parsed_data
      self.data ||= '{}'
      JSON.parse( self.data )
    end

    def item ( key, value )
      data                = parsed_data
      data[key.downcase]  = value
      data                = Hash[data.sort_by { |key, value| key }]
      self.data = data.to_json
      save
    end

    def delete_item ( key )
      data = parsed_data
      data.delete key
      self.data = data.to_json
      save
    end

  end
end

app/models/bagboy/user.rb
module Bagboy
  class User < ActiveRecord::Base
    has_secure_password

    validates_uniqueness_of :email
    validates_presence_of   :email
    validates_presence_of   :password, on: :create
  end
end

app/controllers/bagboy/application_controller.rb
module Bagboy
  class ApplicationController < ActionController::Base
    
    before_action :authorize

    def initialize
      super
      @bag_helper = Bagboy::Chef::DataBagsHelper.instance
      @bags       = @bag_helper.data_bags
      @scm        = Bagboy::Core::SCMHelper.instance
    end

    private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def authorize
      if !session_whitelist?
        redirect_to bagboy_signin_path unless current_user
      end
    end

    def session_whitelist?
      return true if params[:controller] == 'bagboy/sessions'
      if params[:controller] == 'bagboy/users'
        return true if Bagboy::User.count == 0 and (params[:action] == 'new' or params[:action] == 'create')
      end
      false
    end

  end
end

app/controllers/bagboy/data_bag_items_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class DataBagItemsController < ApplicationController

    def index
      @bag  = @bag_helper.data_bag( params[:bag] )
      @item = @bag.item( params[:item] )

      render :index
    end

    def edit
      @bag      = @bag_helper.data_bag( params[:bag] )
      @item     = @bag.item( params[:item] )
      @template = Template::find_or_create_by({data_bag_name: @bag.name})

      render :edit
    end

    def update
      @bag      = @bag_helper.data_bag( params[:bag] )
      @item     = @bag.item( params[:item] )
      @template = Template::find_or_create_by({data_bag_name: @bag.name})

      @item.update params[:data_bag_template_item].permit!, @template.parsed_data

      redirect_to data_bag_items_path({bag: @bag.name, item: @item.name})
    end

    def new
      @bag      = @bag_helper.data_bag( params[:bag] )
      @item     = Chef::DataBags::Item.new
      @template = Template::find_or_create_by({data_bag_name: @bag.name})

      render :new
    end

    def create
      @bag      = @bag_helper.data_bag( params[:bag] )
      @item     = @bag.item params[:data_bag_template_item][:name]
      @template = Template::find_or_create_by({data_bag_name: @bag.name})

      @item.update params[:data_bag_template_item_data].permit!, @template.parsed_data

      redirect_to data_bag_items_path({bag: @bag.name, item: @item.name})
    end

  end
end

app/controllers/bagboy/data_bag_template_items_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class DataBagTemplateItemsController < ApplicationController

    def create
      bag       = @bag_helper.data_bag params[:bag]
      template  = Template::find_or_create_by({data_bag_name: bag.name})

      template.item( params[:data_bag_template_item][:name], params[:data_bag_template_item][:type] )

      redirect_to data_bag_template_path( bag.name )
    end

    def delete
      bag       = @bag_helper.data_bag params[:bag]
      template  = Template::find_or_create_by({data_bag_name: bag.name})

      template.delete_item( params[:data_bag_template_item][:name] )

      redirect_to data_bag_template_path( bag.name )
    end

  end
end

app/controllers/bagboy/data_bag_templates_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class DataBagTemplatesController < ApplicationController

    def show
      @bag      = @bag_helper.data_bag( params[:bag] )
      @template = Template::find_or_create_by({data_bag_name: @bag.name})
      render :show
    end

    def edit
      render :edit
    end
  end
end

app/controllers/bagboy/data_bags_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class DataBagsController < ApplicationController

    def index
      render :index
    end

    def show
      @bag    = @bag_helper.data_bag params[:bag]
      @items  = @bag.items
      render :show
    end

    def new
      @bag = Bagboy::Chef::DataBags::Bag.new
      render :new
    end

    def create
      opts          = data_bag_params
      opts[:path]   = @bag_helper.data_bag_directory( opts[:name] )
      @bag          = Bagboy::Chef::DataBags::Bag.new( opts )

      if @bag.create
        redirect_to data_bags_path
      else
        render :new
      end
    end

    private

    def data_bag_params
      params.require(:data_bag).permit(:name, :path)
    end

  end
end

app/controllers/bagboy/pages_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class PagesController < ApplicationController

    def index
      render :index
    end

    def update
      if @scm.pull
        flash = { success: 'You have successfully updated your chef-repo' }
      else
        flash = { error: 'Something went wrong' }
      end
      redirect_to request.referer, flash: flash
    end

  end
end

app/controllers/bagboy/sessions_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class SessionsController < ApplicationController

    def new
      render 'new'
    end

    def create
      user = Bagboy::User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, flash: {success: 'You have successfuly logged in!'}
      else
        flash.now.alert = 'Invalid email or password'
        render "new"
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_url, flash: { success: 'You have successfuly logged out!'}
    end

  end
end

app/controllers/bagboy/users_controller.rb
require_dependency "bagboy/application_controller"

module Bagboy
  class UsersController < ApplicationController

    def show
      @user = Bagboy::User.find(params[:id])
      render :show
    end

    def index
      @users = Bagboy::User.all
      render :index
    end

    def new
      @user = Bagboy::User.new
      render :new
    end

    def create
      @user = Bagboy::User.new(user_params)
      if @user.save
        redirect_to users_path, flash: { success: "You have succesfully created #{@user.email}"}
      else
        render 'new'
      end
    end

    def edit
      @user = Bagboy::User.find(params[:id])
      render :edit
    end

    def update
      @user = Bagboy::User.find(params[:id])
      @user.update_attributes( user_params )
      if ( @user.save )
        redirect_to user_path( @user.id ), flash: { success: "You have succesfully updated #{@user.email}!"}
      else
        render :edit
      end
    end

    def delete
      @user = Bagboy::User.find(params[:id])
      @user.delete
      redirect_to users_path, flash: { success: "#{@user.email} successfuly deleted!"}
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

  end
end

app/helpers/bagboy/application_helper.rb
module Bagboy
  module ApplicationHelper
  end
end

app/helpers/bagboy/pages_helper.rb
module Bagboy
  module PagesHelper
  end
end

app/helpers/bagboy/sessions_helper.rb
module Bagboy
  module SessionsHelper
  end
end

app/helpers/bagboy/users_helper.rb
module Bagboy
  module UsersHelper
  end
end

app/views/bagboy/data_bag_items/_form.html.haml
- template.parsed_data.each do |key, value|
  .row
    .large-2.columns
      %label.right.inline{ for: "#{namespace}_#{key}" }= key
    .large-10.columns
      - if value == 'text'
        %input{ type: 'text', id: "#{namespace}_#{key}", name: "#{namespace}[#{key}]", placeholder: '', value: item.data[key] || '' }
      - elsif value == 'password'
        %input{ type: 'text', id: "#{namespace}_#{key}", name: "#{namespace}[#{key}]", placeholder: '', value: '' }
        %span.secondary.label{ style: 'margin-bottom: 1em'} Leave blank to not change password
      - elsif value == 'array'
        - @item.data[key].to_a.each do |data_item|
          %input{ type: 'text', id: "#{namespace}_#{key}", name: "#{namespace}[#{key}][]", placeholder: '', value: data_item || '' }
        %div{id: "array_#{key}"}
        - div_id  = "#array_#{key}"
        - id      = "#{namespace}_#{key}"
        - name    = "#{namespace}[#{key}][]"
        %a.button.tiny.success{ href: '#', id: "array_button_#{key}", onclick: "addElement('#{div_id}','#{id}','#{name}')" }
          %i.fa.fa-plus
          Add Item

app/views/bagboy/data_bag_items/edit.html.haml
%h1= "Editing #{@item.name}"

.button-bar
  %ul.button-group
    %li
      %a.button.tiny{href: data_bag_items_path({bag: @bag.name, item: @item.name})}= "Back to #{@item.name}"
  %ul.button-group
    %li
      %a.button.tiny{href: data_bag_path(@bag.name)}= "Back to #{@bag.name}"

%hr

%form{ action: update_data_bag_item_path({bag: @bag.name, item: @item.name}), method: 'post' }
  = render 'form', template: @template, item: @item, namespace: 'data_bag_template_item'
  .row
    .large-2.columns
    .large-10.columns
      %button.button.small{ type: 'submit' } Submit

app/views/bagboy/data_bag_items/index.html.haml
%h1= "Item: #{@item.name}"
%h3.subheader= "From #{@bag.name} data bag"

.button-bar
  %ul.button-group
    %li
      %a.button.tiny{href: edit_data_bag_item_path({bag: @bag.name, item: @item.name})} Edit
  %ul.button-group
    %li
      %a.button.tiny{href: data_bag_path(@bag.name)}= "Back to #{@bag.name}"

%hr

%table
  %thead
    %tr
      %th{ width: '200' } Key
      %th Value
  %tbody
    - @item.data.each do |key, value|
      %tr
        %td= key
        %td
          - if value.kind_of?(Array)
            %ul
              - value.each do |value_item|
                %li= value_item
          - else
            = value

app/views/bagboy/data_bag_items/new.html.haml
%h1 New Item

.button-bar
  %ul.button-group
    %li
      %a.button.tiny{href: data_bag_path(@bag.name)}= "Back to #{@bag.name}"

%hr

%form{ action: create_data_bag_item_path({bag: @bag.name}), method: 'post' }
  .row
    .large-2.columns
      %label.right.inline{ for: "data_bag_template_item" } Name
    .large-10.columns
      %input{ type: 'text', id: "data_bag_template_item", name: "data_bag_template_item[name]"}
  %hr
  = render 'form', template: @template, item: @item, namespace: 'data_bag_template_item_data'

  .row
    .large-2.columns
    .large-10.columns
      %button.button.small{ type: 'submit' } Submit